---
apiVersion: v1
kind: Namespace
metadata:
  name: glimmermeeting
  labels:
    app: glimmermeeting
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: glimmermeeting
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: glimmermeeting
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: glimmermeeting
  ports:
    - port: 2023
      targetPort: 2023
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: glimmermeeting
subsets:
  - addresses:
      - ip: 192.168.79.11
    ports:
      - name: mysql
        port: 3306
        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: glimmermeeting
spec:
  selector:
    matchLabels:
      app: glimmermeeting
  replicas: 2
  template:
    metadata:
      labels:
        app: glimmermeeting
    spec:
      containers:
        - name: backend
          image: backend
          imagePullPolicy: Never
          ports:
            - containerPort: 2023